import { Entity, PrimaryGeneratedColumn, ManyToOne, ManyToMany, JoinTable, Column, CreateDateColumn } from 'typeorm';
import { User } from './user.entity';
import { Product } from './product.entity';

/**
 * Entidad `Order`
 * 
 * Representa una orden de compra dentro del sistema.
 * Cada orden pertenece a un usuario y puede contener múltiples productos.
 * 
 * Esta entidad se mapea directamente a la tabla `order` en la base de datos
 * mediante TypeORM.
 */
@Entity()
export class Order {
  /**
   * Identificador único de la orden.
   * 
   * @type {number}
   * @generated Valor autoincremental generado automáticamente por la base de datos.
   * @example 1
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Usuario que realiza la orden.
   * 
   * Relación *muchas órdenes pertenecen a un usuario* (`ManyToOne`).
   * 
   * @type {User}
   * @relation User → Order
   * @example { id: 2, name: "Ana López", email: "ana@example.com" }
   */
  @ManyToOne(() => User, (user) => user.id)
  user: User;

  /**
   * Lista de productos incluidos en la orden.
   * 
   * Relación *muchos a muchos* (`ManyToMany`) entre `Order` y `Product`.
   * 
   * La tabla intermedia se crea automáticamente mediante `@JoinTable()`.
   * 
   * @type {Product[]}
   * @example [
   *   { id: 1, name: "Aceite de coco", price: 15000 },
   *   { id: 2, name: "Miel natural", price: 12000 }
   * ]
   */
  @ManyToMany(() => Product)
  @JoinTable()
  products: Product[];

  /**
   * Total de la orden expresado en moneda local.
   * 
   * Calculado a partir de la suma de los precios de los productos.
   * 
   * @type {number}
   * @precision 10
   * @scale 2
   * @example 27000.00
   */
  @Column('decimal', { precision: 10, scale: 2 })
  total: number;

  /**
   * Fecha y hora en que se creó la orden.
   * 
   * Se genera automáticamente al crear el registro.
   * 
   * @type {Date}
   * @autoGenerated Sí
   * @example "2025-10-12T15:34:22.000Z"
   */
  @CreateDateColumn()
  createdAt: Date;
}
